spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/kuafor_rez_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

